# Generated by Django 4.2.11 on 2024-04-04 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('stauts', models.IntegerField()),
                ('duration', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaceChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqno', models.IntegerField()),
                ('joined_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FaceChatTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='facechats.facechat')),
            ],
        ),
    ]
